cowin:
  baseUrl : https://cdn-api.co-vin.in/api/v2/
  districtURI: appointment/sessions/calendarByDistrict?
  districtParam: district_id
  date: date
  selectedDistrict: pune

telegram:
    tBaseUrl: https://api.telegram.org
    tApiKey: 1847492768:AAFhDHo_UCJ9G-S8D6pbZWsOE8SaPtYNBWY
    tChannelName : vcpunedistrict

districts:
  all:
    pune: 363